### PR TITLE
Player tracking

### PR DESCRIPTION
**Pull request by ahrayahlabcoimin**

### CODE REVIEW

**Comment by ahrayahlabcoimin** [comment]
TurnContext is a step above a turn tracker because it contextualizes the game in perspective of the active player. Each turn switch just switches who is the player and who is the opponent. It also notifies listeners when the active player changes, including when the game is reset. T

**Review by SangJinHyun — COMMENTED** [review]
See some better naming conventions that seem to work pretty well. Good job. I'll have to take a look at GameManager more but everything else looks fine.

**Comment by EXC3ll3NTrhyTHM** [comment]
Looks good we can merge

**Review by EXC3ll3NTrhyTHM — APPROVED** [review]

**Review by SangJinHyun — APPROVED** [review]

**Comment by EXC3ll3NTrhyTHM** [comment]
SuceedingUnitTestsForACsBranch

**Pull request merged**
